[package]
name = "oxidar_derive"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE.md"
description = "Derive macros for Oxidar"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.94"
quote = "1.0.39"
syn = "2.0.99"
